#!/usr/bin/env node
// Generates play/ttt.md: a fully playable, perfect-play tic-tac-toe opponent
// with no server, no GitHub Action, and no JavaScript.
//
// The whole game tree is pre-rendered as nested <details>. Every move you can
// make is a disclosure triangle; opening it reveals the board after the
// computer has replied with a minimax-optimal move. There is no runtime at
// all, so it cannot break, cannot be rate limited, and will still work in ten
// years. It is also unwinnable, which is the joke.
//
// Written once, committed, never touched again.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const HUMAN = 'X';
const CPU = 'O';

const LINES = [
  [0, 1, 2], [3, 4, 5], [6, 7, 8],
  [0, 3, 6], [1, 4, 7], [2, 5, 8],
  [0, 4, 8], [2, 4, 6],
];

const winner = (b) => {
  for (const [a, c, d] of LINES) if (b[a] && b[a] === b[c] && b[a] === b[d]) return b[a];
  return b.every(Boolean) ? 'draw' : null;
};

const free = (b) => b.map((v, i) => (v ? -1 : i)).filter((i) => i >= 0);

// Depth-aware so the computer wins as fast as possible and loses as slowly as
// possible. Without the depth term it plays "correctly" but makes visibly
// stupid-looking delays before finishing you off.
function minimax(b, turn, depth) {
  const w = winner(b);
  if (w === CPU) return { score: 10 - depth };
  if (w === HUMAN) return { score: depth - 10 };
  if (w === 'draw') return { score: 0 };

  let best = null;
  for (const i of free(b)) {
    b[i] = turn;
    const { score } = minimax(b, turn === CPU ? HUMAN : CPU, depth + 1);
    b[i] = '';
    if (
      best === null
      || (turn === CPU ? score > best.score : score < best.score)
    ) best = { score, move: i };
  }
  return best;
}

const board = (b) => {
  const cell = (i) => b[i] || String(i + 1);
  const row = (r) => [0, 1, 2].map((c) => cell(r * 3 + c)).join(' ');
  return '```\n' + [0, 1, 2].map(row).join('\n') + '\n```';
};

let nodes = 0;
let leaves = { draw: 0, cpu: 0, human: 0 };

/** Renders every human option at this position, recursively. */
function options(b, indent) {
  const out = [];
  for (const move of free(b)) {
    nodes += 1;
    const next = [...b];
    next[move] = HUMAN;

    let status;
    let after = next;
    const afterHuman = winner(next);

    if (afterHuman) {
      status = afterHuman === 'draw' ? '**Draw.** Best available.' : '**You win.** This should be unreachable, please open an issue.';
      leaves[afterHuman === 'draw' ? 'draw' : 'human'] += 1;
    } else {
      const reply = minimax(next, CPU, 0).move;
      after = [...next];
      after[reply] = CPU;
      const afterCpu = winner(after);
      if (afterCpu === CPU) { status = `Computer takes **${reply + 1}**. **Computer wins.**`; leaves.cpu += 1; }
      else if (afterCpu === 'draw') { status = `Computer takes **${reply + 1}**. **Draw.** Well played.`; leaves.draw += 1; }
      else status = `Computer takes **${reply + 1}**. Your move.`;
    }

    // Deliberately NOT indented. The nesting is structural via the HTML tags;
    // indenting it would put deep branches past four leading spaces, and
    // markdown would render them as code blocks instead of game boards.
    out.push(`<details><summary><code>play ${move + 1}</code></summary>`);
    out.push('');
    out.push(board(after));
    out.push('');
    out.push(status);
    out.push('');
    if (!winner(after)) out.push(...options(after, indent + 1));
    out.push('</details>');
    out.push('');
  }
  return out;
}

const empty = new Array(9).fill('');
const body = options(empty, 0);
const total = leaves.draw + leaves.cpu + leaves.human;

const doc = `# Tic-tac-toe

No server. No GitHub Action. No JavaScript. You still cannot win.

The entire game tree is pre-rendered below as nested disclosure triangles. Every
move you can make is already here, along with the computer's minimax-optimal
reply. Click your move, read the board, click your next move.

You are \`X\` and you move first, which is the larger advantage in this game.
Numbers mark the empty squares.

\`\`\`
1 2 3
4 5 6
7 8 9
\`\`\`

Of the ${total.toLocaleString('en-US')} games reachable from here, **${leaves.cpu.toLocaleString('en-US')} end with the computer winning**
and **${leaves.draw.toLocaleString('en-US')} end in a draw**. None end with you winning. A draw is a perfect score.

---

${body.join('\n')}

---

Generated by [\`scripts/gen-ttt.mjs\`](../scripts/gen-ttt.mjs) from a depth-aware minimax search:
${nodes.toLocaleString('en-US')} positions, committed once, zero runtime cost forever.

[Back to the profile](https://github.com/UbhayAab)
`;

mkdirSync(join(ROOT, 'play'), { recursive: true });
const out = join(ROOT, 'play', 'ttt.md');
writeFileSync(out, doc);
console.log(
  `play/ttt.md  ${(Buffer.byteLength(doc) / 1024).toFixed(0)} KB  `
  + `${nodes.toLocaleString('en-US')} positions  `
  + `outcomes: ${leaves.cpu} computer wins, ${leaves.draw} draws, ${leaves.human} human wins`
);
if (Buffer.byteLength(doc) > 400 * 1024) {
  console.error('WARNING: over 400 KB, GitHub stops rich-rendering markdown around 512 KB');
  process.exit(1);
}
